### ISSUE TITLE
Issue when uploading signals predictions: ValueError: Variable "ddataDatestamp" is never used.

### ISSUE THREAD

**Issue by marcoloco23** [numerai/numerapi#111]
This seems to occur in the latest version: 2.19.0 when calling

napi.upload_predictions(
            model_id=MODEL_ID,
            df=live_data,
        )

**Comment by jarley-nobrega** [comment]
It looks like the bug has been fixed in the code, but the version has not been updated in the PyPi repository. At https://pypi.org/project/numerapi/ the version still appears as 2.19.0.

**Comment by uuazed** [comment]
My bad, I forgot adding the git tag. the new version, including the bugfix,  has been released just now: https://pypi.org/project/numerapi/2.19.1/
