### ISSUE TITLE
New tournament round ??

### ISSUE THREAD

**Issue by anselal** [numerai/numerapi#2]
Is there a way to check that the new round has began before downloading the tournament file ?

**Comment by wsteitz** [comment]
Hi @anselal, 
I've just added a way to do exactly that, thanks for the suggestion. This will be part of the next release, until then, feel free to use the development version.

**Comment by uuazed** [comment]
Hi @anselal,
I've just added a way to do exactly that, thanks for the suggestion. This will be part of the next release, until then, feel free to test the development version.

**Comment by anselal** [comment]
Thank you very much, this method will be very useful.

**Comment by anselal** [comment]
Also an example would be appreciated
