### ISSUE TITLE
parse_float_string should use Decimal instead of float

### ISSUE THREAD

**Issue by quantverse** [numerai/numerapi#3]
Hi,

thanks for the great work! I have one remark:

I think the `parse_float_string` should parse the string and return `Decimal` instead of float, especially for staking confidences and NMR values. Using floats here leads to awful rounding errors (confidences like `0.04` is turned to `0.040000000000000000832667268468867405317723751068115234375`).

As a best practice, floats should never be used for financial data or fixed point decimals which need to guarantee the precision (confidence here).

Thanks :)

**Comment by uuazed** [comment]
Hey quantverse,

thanks for the excellent suggestion. I switched to `decimal.Decimal`. Available in the current dev version and with the next release.

Cheers
