### ISSUE TITLE
Is the tournament name in daily_submission_performances still correct?

### ISSUE THREAD

**Issue by simpsus** [numerai/numerapi#39]
It returns kazutsugi. Shouldn't it be nomi?

**Comment by uuazed** [comment]
In theory it should be nomi, yes. However, the numerai guys decided to keep the same tournament number (8), to make things easier for us - In some places we have to provide a tournament number, changing it to something other then 8 would have caused some issues without much gain. 
In one of the recent fireside chats, they mentioned that there won't be any additional tournaments in numerai classic. I guess it's time to remove those leftovers from the multi-tournament times from numerapi as well.

**Comment by uuazed** [comment]
I removed some of deprecated functionality related to multi-tournament and added some deprecation warnings to the docs..
