### ISSUE TITLE
interactive console usage / download progress bar

### ISSUE THREAD

**Issue by quantverse** [numerai/numerapi#4]
Hello,

the numerapi uses `tqdm` to display progress bar while downloading dataset. This completely messes up the output if numerapi is used in application which redirects output to a file (non-interactive mode).

Please do not assume that the software using numerapi runs in console and make the interactive output / features configurable.

**Comment by uuazed** [comment]
Hi @quantverse,

unfortunately I cannot reproduce this. Redirecting the output like this `python myscript.py > output.log`, works perfectly fine with `tqdm`, without messing up the log file. Could you please show me how you re-direct the output?

**Comment by quantverse** [comment]
Hi,

good to know! Maybe the reason is that I run the script inside the `docker` container - so if `tqdm` has any stdout redirection detection, it will fail, because I redirect the output of the `docker` rather than redirecting output of the script, which runs inside the container...

**Comment by uuazed** [comment]
Just added an optional flag to turn progress bars off. Let me know if this helps
