### ISSUE TITLE
Send "source" field during createSubmission

### ISSUE THREAD

**Issue by ndharasz** [numerai/numerapi#61]
Numerai recently introduced an optional "source" field on submissions that can help us gather statistics on how each user is submitting to the tournament. This is as easy as including the field `source: String` here:
- NumerAPI: https://github.com/uuazed/numerapi/blob/6924adf5f8a5fa450948172f3c9e41dd1bb593b5/numerapi/numerapi.py#L614-L628
- SignalsAPI: https://github.com/uuazed/numerapi/blob/6924adf5f8a5fa450948172f3c9e41dd1bb593b5/numerapi/signalsapi.py#L132-L143

and then adding the `"source": "numerapi"` in this dict:
- NumerAPI: https://github.com/uuazed/numerapi/blob/6924adf5f8a5fa450948172f3c9e41dd1bb593b5/numerapi/numerapi.py#L629-L633
- SignalsAPI: https://github.com/uuazed/numerapi/blob/6924adf5f8a5fa450948172f3c9e41dd1bb593b5/numerapi/signalsapi.py#L144-L146

There's a 1 NMR bounty available for completing this

**Comment by uuazed** [comment]
implemented. I just hardcoded the source to numerapi, no need to pass arguments around. 

You might want to add a `source` field to the diagnostics upload as well
