### ISSUE TITLE
API for submitting and getting numbers from Newly introduced "Diagnostics Tool"

### ISSUE THREAD

**Issue by anandi1989** [numerai/numerapi#64]
Previously user can submit prediction and get expected Sharp Ratio, Corr, MMC information . Now that Numerai introduced new tool "Diagnostics Tool"  - Can we have API for the same.

**Comment by uuazed** [comment]
You can already do that like this for "classic"
```
>>> napi = NumerAPI(secret_key="..", public_id="..")
>>> model_id = napi.get_models()['uuazed']
>>> api.upload_diagnostics("prediction.cvs", model_id=model_id)
'93c46857-fed9-4594-981e-82db2b358daf'
>>> napi.diagnostic(model_id)
{"validationCorrMean": 0.53231,
...
            }
```

**Comment by uuazed** [comment]
In the dev version, this now works for signals as well. Will be available with the next release.

**Comment by anandi1989** [comment]
> In the dev version, this now works for signals as well. Will be available with the next release.

Thanks... That helps. Looking forward to the next release
