### ISSUE TITLE
seeking ways to modify profile information (image, bio) via numerapi

### ISSUE THREAD

**Issue by bitfilms** [numerai/numerapi#65]
Hi there. 

I'm finally using more of the model slots afforded to us tourney participants and I'm running into some things that would be great to automate. I didn't see a way to adjust profile images or bios via numerapi and wanted to log that as an enhancement request.

Thanks!

- chris

**Comment by uuazed** [comment]
It's now possible to update `link` and `bio`of a profile via numerapi.
