### ISSUE TITLE
Methods throw: "ValueError: Your session is invalid or has expired."

### ISSUE THREAD

**Issue by bbrimacombe** [numerai/numerapi#7]
The following NumerAPI functions throw "ValueError: Your session is invalid or has expired.". I suspect it is due to outdated GraphQL queries to the Numerai endpoint (or it is a problem on my end, though I've tried to exhaust this possibility):
get_user()
get_payments()
get_transactions()
get_stakes()

**Comment by uuazed** [comment]
Hey, I guess you inadvertently reversed your `public_id` and your `secret_key`. Could you try it the other way around and report back?  Unfortunately, the error message isn't very helpful in that case

**Comment by bbrimacombe** [comment]
Turns out for public_id I was using my "username" as opposed to the public_id code. Thank you for your help
