### ISSUE TITLE
napi.download_dataset() corrupts previously existing parquet files

### ISSUE THREAD

**Issue by emanuele** [numerai/numerapi#76]
According to @jaqume on the Numerai forum, https://forum.numer.ai/t/v4-train-parquet-changed-from-311-to-312/5277 , `napi.download_dataset()` sometimes corrupts previously existing parquet files. I'm submitting an issue here so that the problem/discussion does not go unnoticed.

**Comment by uuazed** [comment]
should be fixed with numerapi 2.12.0. Files are now downloaded to a temporary path first.
