### ISSUE TITLE
Timeout Error: HTTPSConnectionPool(host='api-tournament.numer.ai', port=443)

### ISSUE THREAD

**Issue by mohuzi** [numerai/numerapi#79]
When using upload prediction, keep getting timeout error.
`napi.upload_predictions('./xxx.csv',   model_id = 'xxx' )`

`ERROR numerapi.utils: Timeout Error: HTTPSConnectionPool(host='api-tournament.numer.ai', port=443): Read timed out. (read timeout=3)`

**Comment by ajenningsfrankston** [comment]
It uploads the prediction ok, but fails on constructing the string that is returned.

**Comment by ajenningsfrankston** [comment]
I get the timeout error and this:

609 'triggerId': os.getenv('TRIGGER_ID', None)}
610 create = self.raw_query(create_query, arguments, authorization=True)
--> 611 submission_id = create['data']['create_submission']['id']
612 return submission_id
613

KeyError: 'data'

**Comment by uuazed** [comment]
Fixed with numerapi 2.12.1. thanks for reporting the issue!
