### ISSUE TITLE
daily_submissions_performances returns results even after rounds is resolved

### ISSUE THREAD

**Issue by nate331** [numerai/numerapi#88]
Hi,

I use numerapi to get the final rounds results for my models. In the past I did this the following way:
```
df = pd.DataFrame(napi.daily_submissions_performances(model_name))
data = df.sort_values(by="date").groupby("roundNumber").last()
```
However, this suddenly gave me wrong results. I found out that numerapi is returning the results for each model even beyond the 20 days of the round. This behaviour seems strange to me.
To make it work again I had to change the code to the following: 
```
df = pd.DataFrame(napi.daily_submissions_performances(model_name))
data = df.sort_values(by="date").groupby("roundNumber").nth(19)
```
Is this behaviour intended?

**Comment by uuazed** [comment]
Talking with the numerai team, this endpoint " dailySubmissionPerformances is now returning CORJ60 scores so it will go up to 60 " days. That explains those extra entries. 

Thanks for reporting the issue!
