### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by algonell** [numerai/numerapi#89]
Just tried to download data for the new tournament...

![Screenshot from 2022-10-29 21-55-05](https://user-images.githubusercontent.com/4669001/198848534-52b0e9aa-84ee-4ac2-9f38-dc901a48c606.png)

**Comment by jfjensen** [comment]
same problem here

**Comment by uuazed** [comment]
Apparently a problem on numerai's end, which they fixed now.
