### ISSUE TITLE
How to upload predictions for the validation set ? 

### ISSUE THREAD

**Issue by lcrmorin** [numerai/numerapi#99]
Maybe I am missing something but I can't see how to upload predictions for the validation set and get back evaluation metrics. Is this implemented or not ?

**Comment by uuazed** [comment]
That's implemented:

    # using the diagnostics tool
    napi.upload_diagnostics("preds.csv", model_id=model_id)
    # ... or using a pandas DataFrame directly
    napi.upload_diagnostics(df=df, model_id=model_id)
    # fetch results
    napi.diagnostic(model_id)
